language:
    csharp
    
os:
  - linux
  - osx
dist: trusty
mono: latest
dotnet: 1.1
install:
    - dotnet restore 


before_script:
    - nuget restore ./AuthorizeNET/AuthorizeNET/AuthorizeNET.csproj
    - nuget restore ./SampleCode/SampleCode/SampleCode.csproj
    - nuget restore ./SampleCode/SampleCodeTest/SampleCodeTest.csproj
    - git submodule update --remote --recursive
  
script:
    - dotnet build
    - msbuild ./AuthorizeNET/AuthorizeNET/AuthorizeNET.csproj
    

    - cp ./AuthorizeNET/AuthorizeNET/bin/Debug/netcoreapp1.1/AuthorizeNET.dll ./SampleCode/SampleCode/    
    - msbuild ./SampleCode/SampleCode/SampleCode.csproj
    - msbuild ./SampleCode/SampleCodeTest/SampleCodeTest.csproj 
    
    - dotnet test ./SampleCode/SampleCodeTest/SampleCodeTest.csproj 