language:
    csharp
    
os:
  - linux
  - osx
sudo:
    required
dist: trusty
 # install:
    # - sudo apt-get install nunit-console
mono: latest
env:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true

before_script:
    - nuget restore ./AuthorizeNET/AuthorizeNET/AuthorizeNET.csproj
    - nuget restore ./SampleCode/SampleCode/SampleCode.csproj
    - nuget restore ./SampleCode/SampleCodeTest/SampleCodeTest.csproj
    - git submodule update --remote --recursive
  
script:
    - msbuild ./AuthorizeNET/AuthorizeNET/AuthorizeNET.csproj
    
#   make mono happy by copying the config file with project name
     # - cp AuthorizeNETtest/App.config AuthorizeNETtest/AuthorizeNETtest.config
     # - nunit-console ./AuthorizeNETtest/AuthorizeNETtest.csproj -run=AuthorizeNet.Api.Controllers.MockTest -exclude Integration,NotWorkingOnMono
    # - ls ./AuthorizeNET/AuthorizeNET/bin
    # - ls ./AuthorizeNET/AuthorizeNET/bin/Debug
    # - ls ./AuthorizeNET/AuthorizeNET/bin/Debug/netcoreapp1.1
    - cp ./AuthorizeNET/AuthorizeNET/bin/Debug/netcoreapp1.1/AuthorizeNET.dll ./SampleCode/SampleCode/    
    - msbuild ./SampleCode/SampleCode/SampleCode.csproj
    - msbuild ./SampleCode/SampleCodeTest/SampleCodeTest.csproj 
    
    - mono ./SampleCode/SampleCodeTest/bin/Debug/netcoreapp1.1/SampleCodeTest.dll