language:
    csharp
    
os:
  - linux
  - osx

install:
    - sudo apt-get install nunit-console

before_script:
    - git submodule update --remote --recursive
  
script:
    - xbuild ./Authorize.NET/AuthorizeNET.csproj
    - xbuild ./AuthorizeNETtest/AuthorizeNETtest.csproj
#   make mono happy by copying the config file with project name
    - cp AuthorizeNETtest/App.config AuthorizeNETtest/AuthorizeNETtest.config
    - nunit-console ./AuthorizeNETtest/AuthorizeNETtest.csproj -run=AuthorizeNet.Api.Controllers.MockTest -exclude Integration,NotWorkingOnMono

    - cp ./Authorize.NET/bin/Debug/AuthorizeNet.dll ./sample-code-csharp/
    - xbuild ./SampleCode/SampleCode.csproj
    - xbuild ./SampleCode/SampleCodeTest/SampleCodeTest.csproj 
    - nunit-console ./SampleCode/SampleCodeTest/SampleCodeTest.csproj -run=SampleCodeTest