language:
    csharp

os:
  - linux  

install:    
    - sudo apt-get install nunit-console
    
script:
    - xbuild ./SampleCode.csproj 
    - xbuild ./SampleCodeTest/SampleCodeTest.csproj 
    - nunit-console ./SampleCodeTest/SampleCodeTest.csproj
