language:
    csharp
    
matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
    - os: osx 
      dotnet: 1.0.0-preview2-003121
install:
    - dotnet restore
before_script:
    - nuget restore ./AuthorizeNET/AuthorizeNET/AuthorizeNET.csproj
    - nuget restore ./SampleCode/SampleCode/SampleCode.csproj
    - nuget restore ./SampleCode/SampleCodeTest/SampleCodeTest.csproj
    - git submodule update --remote --recursive
  
script:
    - msbuild ./AuthorizeNET/AuthorizeNET/AuthorizeNET.csproj
    
#   make mono happy by copying the config file with project name
     # - cp AuthorizeNETtest/App.config AuthorizeNETtest/AuthorizeNETtest.config
     # - nunit-console ./AuthorizeNETtest/AuthorizeNETtest.csproj -run=AuthorizeNet.Api.Controllers.MockTest -exclude Integration,NotWorkingOnMono
    # - ls ./AuthorizeNET/AuthorizeNET/bin
    # - ls ./AuthorizeNET/AuthorizeNET/bin/Debug
    # - ls ./AuthorizeNET/AuthorizeNET/bin/Debug/netcoreapp1.1
    - cp ./AuthorizeNET/AuthorizeNET/bin/Debug/netcoreapp1.1/AuthorizeNET.dll ./SampleCode/SampleCode/    
    - msbuild ./SampleCode/SampleCode/SampleCode.csproj
    - msbuild ./SampleCode/SampleCodeTest/SampleCodeTest.csproj 
    - dotnet run ./SampleCode/SampleCodeTest/SampleCodeTest.csproj 