language:csharp
dist: trusty
mono: none
dotnet: 1.1.0

os:
  - linux  

install:
    - dotnet restore
    # # - nuget restore SampleCode.sln
    # - sudo apt-get install nunit-console
    
script:
    -./SampleCode.csproj 
    -./SampleCodeTest.csproj 
    -./SampleCodeTest/SampleCodeTest.csproj
