language:csharp
dist: trusty
mono: none
dotnet: 1.1.0
os:
  - linux  

install:
    - dotnet restore
    - sudo apt-get install nunit-console
script:
    - xbuild ./SampleCode.csproj 
    - xbuild ./SampleCodeTest.csproj 
    - nunit-console ./SampleCodeTest/SampleCodeTest.csproj
